### PR TITLE
256 filter events by config

### LINKED ISSUE #256: filter events by notification config
## Is your feature request related to a problem? Please describe

Able to restrict events to a notification config

## Acceptance Criteria

- [ ] Link to recent events from the notification config page

### PR DESCRIPTION
**Pull request by lache-melvin**
Closes #256 

# 👩🏻‍💻 What does this PR do?
 

Adds a Filter by Notification Config button to the events list:
Screenshot 2023-11-21 at 5 02 30 PM

Clicking this button opens a list, where you can search for and select the config to filter by: 
Screenshot 2023-11-21 at 5 02 36 PM

This puts the config id in the url, filters the events, and replaces the Filter By button with the name of the config we are currently filtering on:
Screenshot 2023-11-21 at 5 02 18 PM

Opening the filter modal again, the Clear Filter button becomes available:
Screenshot 2023-11-22 at 9 10 52 AM

Also adds a button on the edit notification config page, linking to this filtered view of events for that config:
Screenshot 2023-11-21 at 5 01 18 PM

# 🧪 How has/should this change been tested?

## 💌 Any notes for the reviewer?

For some reason, any interaction with the keyboard while the modal is open causes the filter button to be in focus when it closes??? i.e. if you scroll and click, it's fine, but if you search and then click, this happens:

Screenshot 2023-11-21 at 4 57 42 PM

This seems very confusing to me, like I'm being summoned to open the modal again... I tried a couple of things but not sure why it's only when you use keyboard interactions. There is an option to disable the ripple effect for any keyboard focus on the button, but that's a loss for accessibility... which would be better for now??

### CODE REVIEW

**Comment by jmbrunskill** [comment]
> This seems very confusing to me, like I'm being summoned to open the modal again... I tried a couple of things but not sure why it's only when you use keyboard interactions. There is an option to disable the ripple effect for any keyboard focus on the button, but that's a loss for accessibility... which would be better for now??

We also have this issue : https://github.com/msupply-foundation/notify/issues/71 is it related?

**Comment by lache-melvin** [comment]
> We also have this issue : #71 is it related?

Mm quite possibly, I think we've got a few default behaviours getting confused with everything we've wrapped around the base MUI components 🥲

**Review by jmbrunskill — APPROVED** [review]
❤️ it!
Super useful.

It was immediately obvious to me that the Recent Events button goes on the top right.
It's consistent with the Notification Config link though, so like it from that perspective.

UX wise, it's super useful to have this feature so people will get used to it.

I'm open to ideas for re-arranging though. The event view feels a bit messy to, but again, it's for admins so they can learn what to click :)

**Comment by lache-melvin** [comment]
> I'm open to ideas for re-arranging though. 

Yeah definitely agree it could use some UX design work, some of it isn't super intuitive at the moment 🥲 

I'll go with disabling the ripple effect, because you still _can_ select the button, and the ripple is quite obviously strange. I've created an issue to review it/the other issues with keyboard interactions... possibly a good mission for next RnD day!

**Pull request merged**
